#from django.conf import settings
from api import config
MEMCACHE_HOST = config.MEMCACHE_HOST
MEMCACHE_PORT = config.MEMCACHE_PORT

MONGO_URI = config.DATA_STORE_MONGO_URI
MONGO_HOST = config.MONGO_HOST
MONGO_PORT = config.MONGO_PORT
MONGO_DB = config.MONGO_DB
MONGO_LOG_COLLECTION = config.MONGO_LOG_COLLECTION
MONGO_TOMBSTONE_COLLECTION = config.MONGO_TOMBSTONE_COLLECTION

BROKER_URL = config.BROKER_URL

CELERY_RESULT_BACKEND = config.CELERY_RESULT_BACKEND
CELERY_MONGODB_BACKEND_SETTINGS = config.CELERY_MONGODB_BACKEND_SETTINGS
